### ISSUE TITLE
Adding a suitable app icon and name

### ISSUE THREAD

**Issue by danger-ahead** [31Carlton7/flutter_notes_app#2]
#### The name has still not been changed from `notes_app`.

Working on these two could increase the appeal of the app to the users.

Loved the UI and working of the app. Would love to collaborate.
If you want me to work on this issue, feel free to assign.
Also I'd need the new icon file and the updated app name as per your wish.

**Comment by 31Carlton7** [comment]
If you would like, you can email me a custom launcher icon in .png format and I'll update the app to include it, because I personally like to do it a certain way.

You can submit a pull request to update the app name to "Notes" as I think it's the most fitting. (I also don't have a very creative name in mind)

Thank you very much for the feedback! Please see the README.md to get an idea of the app's future implementations going forward, and let me know which part you would like to contribute to.

**Comment by danger-ahead** [comment]
> If you would like, you can email me a custom launcher icon in .png format and I'll update the app to include it, because I personally like to do it a certain way.
> 
> You can submit a pull request to update the app name to "Notes" as I think it's the most fitting. (I also don't have a very creative name in mind)
> 
> Thank you very much for the feedback! Please see the README.md to get an idea of the app's future implementations going forward, and let me know which part you would like to contribute to.

Thanks.
I would like to work on the authentication feature. And for this, I'd be using the [local_auth](https://pub.dev/packages/local_auth) package.

Also I'd be changing the name and issuing a PR shortly.

**Comment by 31Carlton7** [comment]
> I would like to work on the authentication feature

This will be good for the lock notes implementation. I previously had one but removed it because I felt like it was too glitchy.

Before implementing this, take a very very VERY good look at the code structure, and if you want me to, I can break it down to demonstrate how it works. It must stay consistent.

Here is a list of steps to complete the process and let me know if something doesn't work.

1. Add a new non nullable bool called `locked` to the `note.dart` model. This is located in `lib/src/models/note.dart`. Add that and update the rest of the parameters and methods to include it.
2. You'll probably notice that there are errors, because you didn't add the locked parameter to certain methods. I think there should be an error in the `_completeNoteFunction()` in the `note_creation_view.dart`, so add the locked parameter and set it to `false`. Do this in any other occurrences you see.
3. Next, Update the `note_card.dart` file to change the title and content if the note is locked. You can add another `if` statement inside of the `_contentText()` method and `_titleText()` methods there. Then update `_body()` to hide the tags if the note is locked. The file is located in `lib/src/ui/components/note_card.dart`
4. Then create a new note card action inside of `lib/src/ui/functions/note_card_functions` and call it `lock_note_action`. Simply copy and paste the code in the `pin_note_action`. then update it to support locking the note, which is just simply changing the bool value. You can change the color of it to purple or green or something that stands out.
5. Implement the new action into the `note_card` in the `actions` list parameter in the `Slidable` widget. (We don't want someone to be able to swipe all the way and lock it).

That should be it. This should work, but I obviously have no clue, and I don't have the time to implement it as of right now. I'm not sure if I went over everything so feel free to ask questions! I am also so sorry that I don't have clear guidelines for code implementations, and I had to describe it to you this way, but I hope this helps. Good Luck!

**Comment by danger-ahead** [comment]
> 1. Add a new non nullable bool called `locked` to the `note.dart` model. This is located in `lib/src/models/note.dart`. Add that and update the rest of the parameters and methods to include it.

Actually I've already started working on this. I am trying to implement a global lock in the app.
This is what I plan to do:
<img src="https://user-images.githubusercontent.com/55531939/141689379-27efa0f0-ada9-4318-b4aa-d21e70f55a1b.png" alt="screenshot" width="200"/>

Should I discard this and work on the individual note locking instead?
We can later add that part too. As I've already coded out most of this feature.
Also I'm following your general code structure and not deviating from your design principles.

**Comment by 31Carlton7** [comment]
The global lock feature is actually very creative. I didn't even think about that. Keep at it with that.

**Comment by danger-ahead** [comment]
> If you would like, you can email me a custom launcher icon in .png format and I'll update the app to include it, because I personally like to do it a certain way.

I've emailed you a custom launcher icon. Do let me know what you think.
